language: php
php:
  - 5.2
  - 5.3
  - 5.4
  
env:
 - WP_VERSION=master 
 - WP_VERSION=3.3.1
 - WP_VERSION=3.2.1

before_script:
  - wget https://raw.github.com/benbalter/wordpress-plugin-tests/setup/setup.sh
  - sh setup.sh
  
script: php wp-test.php -d